version: "3.3"
  
services:
  back-test:
    restart: always
    build:
      context: ./src/back
      dockerfile: ./Dockerfile-test

    image: cdp-g1-eq1-back-test

  db:
    restart: always
    build: 
      context: ./src/bdd
      dockerfile: ./Dockerfile
    environment: 
      MYSQL_DATABASE: 'cdp'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'changeMeLater'
      MYSQL_ROOT_PASSWORD: 'changeMeLater'
    ports:
      - "3307:3306"

    image: cdp-g1-eq1-db-test