name: Front-lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install eslint
      working-directory: ./src/front/
      run: npm i --save eslint

    - name: Init eslint
      working-directory: ./src/front/
      run: ./node_modules/.bin/eslint --init 

    - name: Run ESLint
      working-directory: ./src/front/
      run: ./node_modules/.bin/eslint ./src --ext .ts,.js