name: Front-lint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      working-directory: ./src/front

    steps:
    - name: Run ESLint
    - run: eslint ./src --ext .ts,.js