name: Front-lint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      working-directory: ./src/front

    steps:
    - name: Install eslint
      run: npm i --save eslint

    - name: Init eslint
      run: ./node_modules/.bin/eslint --init 

    - name: Run ESLint
      run: ./node_modules/.bin/eslint ./src --ext .ts,.js